# Generated by Django 5.1 on 2024-08-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=225)),
                ('fname', models.CharField(max_length=225)),
                ('mname', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('course', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=500)),
                ('year', models.IntegerField(max_length=20)),
                ('mobile', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
