# Generated by Django 5.1 on 2024-08-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=200)),
                ('Year', models.IntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('new_file', models.FileField(upload_to='myimage')),
            ],
        ),
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=200)),
                ('Year', models.IntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usm',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=200)),
                ('Year', models.IntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('new_file', models.FileField(upload_to='myimage')),
            ],
        ),
    ]
