# Generated by Django 5.1 on 2024-08-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0003_assignment_lecture_usm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=300)),
                ('contactno', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=300)),
                ('comp', models.CharField(max_length=1000)),
                ('reqdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=300)),
                ('contactno', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=300)),
                ('feed', models.CharField(max_length=1000)),
                ('reqdate', models.DateTimeField()),
            ],
        ),
    ]
