# Generated by Django 5.1 on 2024-08-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0004_complaints_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('contactno', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('enq', models.CharField(max_length=1000)),
                ('enqdate', models.DateTimeField()),
            ],
        ),
    ]
