# Generated by Django 5.1 on 2024-08-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0007_complaints_status_feedbacks_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='reqdate',
            field=models.DateField(),
        ),
    ]
