# Generated by Django 5.1 on 2024-08-31 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0009_alter_feedbacks_reqdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='gender',
        ),
    ]
