# Generated by Django 5.1 on 2024-08-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0010_remove_enquiry_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='noti',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('notm', models.CharField(max_length=200)),
                ('notdate', models.DateTimeField()),
            ],
        ),
    ]
