# Generated by Django 5.1 on 2024-08-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0011_noti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noti',
            name='notdate',
            field=models.CharField(max_length=15),
        ),
    ]
