# Generated by Django 5.1 on 2024-09-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0013_alter_feedbacks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
