# Generated by Django 5.0.6 on 2024-09-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0016_alter_registration_new_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=40)),
                ('adddate', models.DateField()),
            ],
        ),
    ]
