# Generated by Django 5.0.6 on 2024-09-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0018_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course',
            new_name='program',
        ),
    ]
