# Generated by Django 5.0.6 on 2024-09-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0019_rename_course_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='branch',
            new_name='Adbranch',
        ),
    ]
