
from django.urls import path
from .views import*
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', home, name='home'),
    path('layout', layout, name='layout'),
    path('contact', contact, name='contact'),
    path('courses', courses, name='courses'),
    path('ugcourse', ugcourse, name='ugcourse'),
    path('pgcourse', pgcourse, name='pgcourse'),
    path('dpcourse', dpcourse, name='dpcourse'),
    path('cfcourse', cfcourse, name='cfcourse'),
    path('services', services, name='services'),
    path('aboutportal', aboutportal, name='aboutportal'),
    path('viewstudy', viewstudy, name='viewstudy'),
    path('registration', Registration, name='registration'),
    path('save', save_view, name='save'),
    path('adminpanel', studenthome, name='adminpanel'),
    path('homelogin', login, name='homelogin'),
    path('logcode', logcode, name='logcode'),
    path('showdata', showdata, name='showdata'),
    path('courselayout', courselayout, name='courselayout'),
    path('maintenance', maintenance, name='maintenance'),
    path('adminzone', adminhome, name='adminzone'),
    path('uploadstudy', uploadstudy, name='uploadstudy'),
    path('uploadlecture', uploadlecture, name='uploadlecture'),
    path('uploadassignment', uploadassignment, name='uploadassignment'),
    path('updateprofile', updateprofile, name='updateprofile'),
    path('doubt', doubt, name='doubt'),
    path('complain', complain, name='complain'),
    path('feedback', feedback, name='feedback'),
    path('assignments', assignments, name='assignments'),
    path('lectures', lectures, name='lectures'),
    path('studenthome', studenthome, name='adminpanel'),
    path('viewenquiry', viewenquiry, name='viewenquiry'),
    path('feedbackshow', feedbackshow, name='feedbackshow'),
    path('addnotification', addnotification, name='addnotification'),
    path('complainshow', complainshow, name='complainshow'),
    path('usmsave', usmsave, name='usmsave'),
    path('complaintsave/<int:id>', complaintsave, name='complaintsave'),
    path('feedbacksave/<int:id>', feedbacksave, name='feedbacksave'),
    #path('deletenotif/<int:id>', deletenotif, name='deletenotif'),
    path('assignmentsave', assignmentsave, name='assignmentsave'),
    path('lecturesave', lecturesave, name='lecturesave'),
    path('enqsave', enqsave, name='enqsave'),
    path('notisave', notisave, name='notisave'),
    path('uploaddata/<int:id>', uploaddata, name='uploaddata'),
    path('deleteusm/<int:id>', deleteusm, name='deleteusm'),
    path('deleteass/<int:id>', deleteass, name='deleteass'),
    path('deletecomps/<int:id>', deletecomps, name='deletecomps'),
    path('deletefeeds/<int:id>', deletefeeds, name='deletefeeds'),
    #path('adminhome', adminhome, name='adminhome'),
    path('deleteuser/<int:id>', deleteuser, name='deleteuser'),
    path('deletelect/<int:id>', deletelect, name='deletelect'),
    path('deleteenq/<int:id>', deleteenq, name='deleteenq'),
    path('updateform', updateform, name='updateform'),
    path('proupdate', proupdate, name='proupdate'),
    path('upsave', upsave, name='upsave'),
    path('logout', logout, name='logout'),
    path('addcourse',addcourse,name='addcourse'),
    path('coursave',coursave,name='coursave'),
    path('addbranch',addbranch,name='addbranch'),
    path('branchsave',branchsave,name='branchsave'),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
